### ISSUE TITLE
[Feature] 모바일 용 레이아웃

### ISSUE THREAD

**Issue by zaeval** [kmu-total-info-system/locker-system-layout#47]
**Is your feature request related to a problem? Please describe.**
모바일에서 사물함 클릭이 어렵기 때문에, 이를 해결 하고자 함.

**Describe the solution you'd like**
사물함 선택을 드롭박스 형태로도 제공

**Describe alternatives you've considered**
- [ ] 드롭박스( 선택 할 수 있는 사물함만 항목에 있어야함, 학년은 상관없음, 위쪽 사물함 레이아웃의 사물함을 클릭하면 드롭박스도 변해야함.  )
- [ ] 신청하기 버튼 만들기 ( 버튼을 눌렀을 때, 신청 이벤트가 발생해야함. )

**Comment by workdd** [comment]
vuetify로 작업해야하므로 locker-system-nuxt repo 에서 작업하겟습니다
